name: tyba_flutter_challenge
description: Tyba Flutter Challenge.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.1.0
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  google_fonts: ^2.3.1
  page_transition: ^2.0.4
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/


